#!/usr/bin/env python3
"""Lint the UI catalog against the call sites. Runs as a build phase of the QuickTerm target.

Why a build phase and not only a test: the test host is ad-hoc signed, so macOS rebinds its
Documents grant on every rebuild, and this repo lives under ~/Documents — `LocalizationTests`
can only read the source tree once somebody answers a privacy prompt, and skips otherwise. A
build script runs as the developer's own shell, which already has that access, so this check
actually runs for everybody, every build. `LocalizationTests` asserts the same invariants and
is the one that runs in a normal checkout.

What it rejects (each as a `file:line: error:` Xcode shows in the issue navigator):
  * a key used in code that is missing from en.lproj or zh-Hans.lproj;
  * key sets that differ between the two languages;
  * one key declared by two tables of the same language;
  * a format specifier that is not positional (`%1$@`), so a translation can reorder values
    and can never crash `String(format:)`;
  * the two languages filling in different argument positions;
  * a `.one` without its `.other`;
  * a call site gluing a lookup onto something else — the one shape that cannot be translated;
  * a key that no call site asks for (dead weight that still has to be translated);
  * CJK in an English value, or a Chinese value left as the English one without saying so.
"""

import os
import re
import sys

LPROJ = {"en": "en.lproj", "zh": "zh-Hans.lproj"}

# "key" = "value";  — with /* */ comments stripped first, since those quote sample text.
ENTRY = re.compile(r'"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;')
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)
POSITIONAL = re.compile(r"%(\d+)\$@")
CJK = re.compile(r"[\u3000-\u303f\u3400-\u4dbf\u4e00-\u9fff\uff00-\uffef]")
# A Chinese value that is deliberately the English one carries this marker in a comment above it.
SAME_AS_ENGLISH = "same-as-english"


def fail(errors, path, line, message):
    errors.append("%s:%d: error: %s" % (path, line, message))


def check_project_membership(root, resources, errors):
    """Every .strings table is a resource of the app target.

    This project is generated by xcodegen from project.yml, which enumerates Resources at
    generate time: a table added without re-running `xcodegen generate` is simply not copied
    into the bundle. Nothing else notices — the catalog on disk is complete, so this script and
    the key-set tests stay green while the running app quietly draws raw keys like
    `menu.shell.new-terminal` on screen.
    """
    pbxproj = os.path.join(root, "QuickTerm.xcodeproj", "project.pbxproj")
    if not os.path.exists(pbxproj):
        return
    with open(pbxproj, encoding="utf-8") as handle:
        project = handle.read()
    for folder in LPROJ.values():
        directory = os.path.join(resources, folder)
        for name in sorted(os.listdir(directory)):
            if not name.endswith(".strings"):
                continue
            if "%s/%s" % (folder, name) not in project:
                fail(errors, os.path.join(directory, name), 1,
                     "%s/%s is not in the Xcode project — run `xcodegen generate`, or it will "
                     "not be copied into the app bundle" % (folder, name))


# ---------------------------------------------------------------- the catalog


def load_tables(resources):
    """{language: {table name: {key: (value, line)}}}, read from the .strings sources."""
    out = {}
    for language, folder in LPROJ.items():
        directory = os.path.join(resources, folder)
        tables = {}
        for name in sorted(os.listdir(directory)):
            if not name.endswith(".strings") or name == "InfoPlist.strings":
                continue
            path = os.path.join(directory, name)
            with open(path, encoding="utf-8") as handle:
                text = handle.read()
            # Blank the comments but keep the line count, so errors point at the real line.
            text = BLOCK_COMMENT.sub(lambda m: re.sub(r"[^\n]", " ", m.group(0)), text)
            entries = {}
            for match in ENTRY.finditer(text):
                entries[match.group(1)] = (match.group(2), text[: match.start()].count("\n") + 1)
            tables[name[: -len(".strings")]] = (path, entries)
        out[language] = tables
    return out


def merge(tables, errors):
    """One language's tables merged into {key: (value, path, line)}; two owners is an error."""
    merged = {}
    for name, (path, entries) in sorted(tables.items()):
        for key, (value, line) in entries.items():
            if key in merged:
                fail(errors, path, line,
                     '%s is declared in both %s.strings and %s.strings — one key, one owner'
                     % (key, merged[key][3], name))
                continue
            merged[key] = (value, path, line, name)
    return merged


# ------------------------------------------------------------- the call sites


def swift_files(root):
    for base, _, names in os.walk(root):
        for name in sorted(names):
            if name.endswith(".swift"):
                yield os.path.join(base, name)


def string_literals(text, open_paren):
    """The string literals inside one balanced ( … ), mirroring the Swift scanner."""
    out = []
    depth = 0
    i = open_paren
    while i < len(text):
        char = text[i]
        if char == "(":
            depth += 1
            i += 1
        elif char == ")":
            depth -= 1
            i += 1
            if depth == 0:
                return out
        elif char == '"':
            literal = ""
            i += 1
            while i < len(text) and text[i] != '"':
                if text[i] == "\\":
                    i += 1
                if i < len(text):
                    literal += text[i]
                i += 1
            i += 1
            out.append(literal)
        else:
            i += 1
    return out


def is_key_shaped(literal):
    """menu.shell.new-terminal — lowercase, dot separated, at least two segments."""
    segments = literal.split(".")
    if len(segments) < 2:
        return False
    return all(segment and re.fullmatch(r"[a-z0-9-]+", segment) for segment in segments)


# L("a.b") / Lp("a.b", count:) in AppKit code, i18n("a.b") / i18n.plural("a.b", count:) inside a
# SwiftUI body — four spellings of one lookup. Missing i18n here would leave every SwiftUI key
# unchecked: a typo there is invisible until a user reads "status.volume.mute" off the screen.
CALL = re.compile(r"(?<![A-Za-z0-9_.])(Lp|L|i18n\.plural|i18n)\(")
PLURAL_CALLS = ("Lp", "i18n.plural")


def scan_call_sites(sources):
    """[(key, path, line)] for every lookup call. A plural call contributes .one and .other."""
    out = []
    for path in swift_files(sources):
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        for match in CALL.finditer(text):
            name = match.group(1)
            literals = [x for x in string_literals(text, match.end() - 1) if is_key_shaped(x)]
            line = text[: match.start()].count("\n") + 1
            if name in PLURAL_CALLS:
                # only the first literal is the base; later arguments may be a nested L(…)
                for key in literals[:1]:
                    out.append((key + ".one", path, line))
                    out.append((key + ".other", path, line))
            else:
                for key in literals:
                    out.append((key, path, line))
    return out


def check_concatenation(sources, errors):
    """`L("a") + name` / `"\\(L("a"))"` cannot be translated: word order differs."""
    lookup = r'(?:Lp|L|i18n\.plural|i18n)'
    glued = re.compile(r'(?<![A-Za-z0-9_.])' + lookup + r'\("[^"\n]+"[^\n]*\)\s*\+'
                       r'|\+\s*(?<![A-Za-z0-9_.])' + lookup + r'\("'
                       r'|\\\(\s*' + lookup + r'\(')
    for path in swift_files(sources):
        with open(path, encoding="utf-8") as handle:
            for number, line in enumerate(handle, start=1):
                if glued.search(line):
                    fail(errors, path, number,
                         "a localized lookup is glued onto something else — make the key a "
                         "whole sentence with %1$@ arguments instead: " + line.strip())


# ------------------------------------------------------------------- the checks


def non_positional(value):
    """Format specifiers that are not %n$@ (and not an escaped %%)."""
    out = []
    i = 0
    while i < len(value):
        if value[i] != "%":
            i += 1
            continue
        j = i + 1
        if j >= len(value):
            out.append("a trailing %")
            break
        if value[j] == "%":
            i = j + 1
            continue
        digits = ""
        while j < len(value) and value[j].isdigit():
            digits += value[j]
            j += 1
        if digits and j + 1 < len(value) and value[j] == "$" and value[j + 1] == "@":
            i = j + 2
            continue
        out.append("%" + digits + (value[j] if j < len(value) else ""))
        i = j + 1
    return out


def same_as_english_keys(resources):
    """Keys whose Chinese value is deliberately the English one, marked in the .strings source.

    The exemption lives next to the value, in the comment above it, rather than in a list
    inside this script — a list here would rot the moment somebody retranslates the entry.
    """
    marked = set()
    directory = os.path.join(resources, LPROJ["zh"])
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".strings"):
            continue
        with open(os.path.join(directory, name), encoding="utf-8") as handle:
            text = handle.read()
        for match in re.finditer(SAME_AS_ENGLISH, text):
            entry = ENTRY.search(text, match.end())
            if entry:
                marked.add(entry.group(1))
    return marked


def check_values(english, chinese, marked, errors):
    """The two halves are really two languages.

    An English value with CJK in it, or a Chinese value left as a copy of the English one, is
    what a half-finished translation pass leaves behind — and neither shows up as a missing key.
    """
    for key, (value, path, line, _) in sorted(english.items()):
        if CJK.search(value):
            fail(errors, path, line,
                 "%s: the English value contains Chinese (%s) — en.lproj is the base language"
                 % (key, CJK.search(value).group(0)))
    for key, (value, path, line, _) in sorted(chinese.items()):
        if key not in english or english[key][0] != value or key in marked:
            continue
        fail(errors, path, line,
             '%s: the Chinese value is the English one, word for word. Translate it, or put a '
             '"%s: <why>" comment above it if it is meant to be identical.'
             % (key, SAME_AS_ENGLISH))


def check_unused(english, used, errors):
    """Every declared key is asked for somewhere.

    A key nobody reads still costs a translation and still has to be kept in step with its twin;
    and a key that *became* unused is the trace of UI that was deleted or of a call site that
    quietly went back to a hard-coded literal.
    """
    for key, (_, path, line, _) in sorted(english.items()):
        if key in used:
            continue
        base, _, suffix = key.rpartition(".")
        if suffix in ("one", "other") and base in used:
            continue
        fail(errors, path, line,
             "%s is declared but no call site asks for it — delete it, or use it" % key)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sources = os.path.join(root, "Sources")
    resources = os.path.join(root, "Resources")
    errors = []

    tables = load_tables(resources)
    catalogs = {language: merge(tables[language], errors) for language in LPROJ}
    english, chinese = catalogs["en"], catalogs["zh"]

    en_path = os.path.join(resources, LPROJ["en"])
    zh_path = os.path.join(resources, LPROJ["zh"])
    if not english:
        fail(errors, en_path, 1, "en.lproj declares no keys at all")

    # Identical key sets. English is the base language: a key only in Chinese is dead weight,
    # a key only in English silently falls back.
    for key in sorted(set(english) - set(chinese)):
        fail(errors, english[key][1], english[key][2],
             "%s is missing from zh-Hans.lproj (add it to the matching table there)" % key)
    for key in sorted(set(chinese) - set(english)):
        fail(errors, chinese[key][1], chinese[key][2],
             "%s is not declared in en.lproj, the base language" % key)

    for language, catalog in (("en", english), ("zh-Hans", chinese)):
        for key, (value, path, line, _) in sorted(catalog.items()):
            for bad in non_positional(value):
                fail(errors, path, line,
                     "%s uses %s; only positional %%1$@, %%2$@ … (or %%%% ) are allowed" % (key, bad))
            # A count-dependent key needs both halves, or Lp falls back mid-sentence.
            for suffix, twin in ((".one", ".other"), (".other", ".one")):
                if key.endswith(suffix) and key[: -len(suffix)] + twin not in catalog:
                    fail(errors, path, line,
                         "%s has no %s (%s)" % (key, key[: -len(suffix)] + twin, language))

    # Both languages fill in the same arguments, or a value drops out of a sentence.
    for key, (value, path, line, _) in sorted(english.items()):
        if key in chinese:
            if set(POSITIONAL.findall(value)) != set(POSITIONAL.findall(chinese[key][0])):
                fail(errors, chinese[key][1], chinese[key][2],
                     "%s does not use the same arguments as the English value" % key)

    # Every key the code asks for is declared in both languages.
    used = scan_call_sites(sources)
    if not used:
        fail(errors, os.path.join(sources, "Localization/Localization.swift"), 1,
             "the call-site scanner found no L(…) calls — it is broken")
    for key, path, line in used:
        if key not in english:
            fail(errors, path, line, "%s is not declared in %s" % (key, en_path))
        if key not in chinese:
            fail(errors, path, line, "%s is not declared in %s" % (key, zh_path))

    check_values(english, chinese, same_as_english_keys(resources), errors)
    # `used` already holds the resolved halves of a plural call site (…​.one / …​.other), and
    # check_unused maps a declared half back onto them. Do NOT also add each key's prefix here:
    # `palette.menu.visible-columns` is the prefix of `palette.menu.visible-columns-value`, and
    # a prefix set would quietly declare half the catalog used.
    check_unused(english, {key for key, _, _ in used}, errors)
    check_concatenation(sources, errors)
    check_project_membership(root, resources, errors)

    for message in sorted(set(errors)):
        print(message)
    if errors:
        print("localization: %d problem(s); see Resources/en.lproj for the rules" % len(set(errors)))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
