import Foundation

/// Layer 3 of the engine config chain (spec §4.7): the overlay file QuickTerm generates.
/// M1 injected a fixed opacity and padding; from M3 on, `ThemeManager` rewrites it for the
/// current theme.
enum EngineOverlay {
    static var url: URL {
        let dir = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("QuickTerm", isDirectory: true)
        return dir.appendingPathComponent("engine-overlay.conf")
    }

    /// Write the overlay file and return its path (nil on failure; the other layers of the
    /// chain are unaffected).
    @discardableResult
    static func install(extra: String = "") -> String? {
        let contents = """
        # Generated by QuickTerm; do not edit by hand, it gets overwritten. Put your own
        # settings in ~/.config/ghostty/config, or in the [ghostty] section of
        # ~/.config/quickterm/config.toml.
        # macOS 26's CVDisplayLink (a deprecated API) has a per-session quota: once enough
        # surfaces have been created, CVDisplayLinkCreateWithActiveCGDisplays starts failing,
        # which shows up as an OOM during surface init.
        # Turning vsync off bypasses DisplayLink entirely (CoreAnimation still throttles
        # rendering).
        # See "DisplayLink session quota" in docs/porting-notes.md.
        window-vsync = false
        \(extra)
        """
        do {
            try FileManager.default.createDirectory(
                at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try contents.write(to: url, atomically: true, encoding: .utf8)
            return url.path
        } catch {
            return nil
        }
    }
}
